fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    sudo: "https://github.com/saz/puppet-sudo.git"
    ssh:
      repo: "https://github.com/jantman/puppet-ssh.git"
      ref: "3af5933387f44a010892d40b7042cff7c7e321dd"
  symlinks:
    archlinux_workstation: "#{source_dir}"
