fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    sudo: "https://github.com/saz/puppet-sudo.git"
    ssh:
      repo: "https://github.com/jantman/puppet-ssh.git"
      ref: "archlinux"
  symlinks:
    archlinux_workstation: "#{source_dir}"
